version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - copyloopvar
    - dupl
    - goconst
    - gocyclo
    - gosec
    - prealloc
    - unconvert
  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G404
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - errcheck
        text: Error return value of.*logger.Log.* is not checked
      - linters:
          - errcheck
        text: Error return value of.*Log.* is not checked
      - linters:
          - gosec
        text: 'G104: Errors unhandled'
        source: logger.Log
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
